# Generated by Django 5.2.17 on 2026-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='special_features',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
